trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(4dcde7ac-537f-41cc-88b0-ce4edcc82eb8)'
    appType: 'webApp'
    WebAppName: 'ori-demo'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'