trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'ori1'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure subscription 1(4dcde7ac-537f-41cc-88b0-ce4edcc82eb8)'
      appType: 'webAppLinux'
      appName: 'ori-demo'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'